apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
  labels:
    app: mlflow
    component: service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: mlflow
    component: server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlflow-ingress
  namespace: mlflow
  labels:
    app: mlflow
    component: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
  - host: mlflow.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mlflow-service
            port:
              number: 5000
  - http:
      paths:
      - path: /mlflow
        pathType: Prefix
        backend:
          service:
            name: mlflow-service
            port:
              number: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlflow
  labels:
    app: mlflow
    component: config
data:
  mlflow.conf: |
    # MLflow Configuration
    backend_store_uri = sqlite:///mlflow/mlflow.db
    default_artifact_root = /mlflow/artifacts
    host = 0.0.0.0
    port = 5000
    serve_artifacts = true
    
    # Logging configuration
    [loggers]
    keys = root
    
    [handlers]
    keys = consoleHandler
    
    [formatters]
    keys = simpleFormatter
    
    [logger_root]
    level = INFO
    handlers = consoleHandler
    
    [handler_consoleHandler]
    class = StreamHandler
    level = INFO
    formatter = simpleFormatter
    args = (sys.stdout,)
    
    [formatter_simpleFormatter]
    format = %(asctime)s - %(name)s - %(levelname)s - %(message)s